export default {
    BOTTOM_TABS : "bottomTabs",
    SETTINGS : "settings",
    SHOP : "shop",
    EXPLORE : "explore",
    CART : "cart",
    FAVOURITE : "favourite",
    COMING_SOON : "comingSoon",
    LOGIN : "login",
    SIGNUP : "signup",
    FORGOT_PASSWORD : "forgotPassword",
    PRODUCT_SCREEN : "productScreen",
    MAP_SCREEN : "mapScreen",
    ADDRESS_SCREEN : "addressScreen",
}